### ISSUE TITLE
wheel 0.42.0 does not sort the tags as change_wheel_version does

### ISSUE THREAD

**Issue by adlotsof** [hauntsaninja/change_wheel_version#2]
removing the `sorted()` around `t.split("."))` when assigning `new_tag` fixes `Failed to create new wheel`

**Comment by hauntsaninja** [comment]
Thanks for the issue! Hm, the `sorted` logic still seems necessary for me.

```
~/dev/change_wheel_version master λ python -m venv env                                                                                                        
~/dev/change_wheel_version master λ source env/bin/activate
(env) ~/dev/change_wheel_version master λ pip install . --quiet       
(env) ~/dev/change_wheel_version master λ pip freeze           
change_wheel_version @ file:///Users/shantanu/dev/change_wheel_version
installer==0.7.0
packaging==23.2
wheel==0.42.0
(env) ~/dev/change_wheel_version master λ python -m change_wheel_version whlz/triton-2.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl  --version 1234 --local-version yikes
original tag cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64
sorted tag cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64
whlz/triton-1234+yikes-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
(env) ~/dev/change_wheel_version master λ ls -1 whlz                  
triton-1234+yikes-cp312-cp312-manylinux2014_x86_64.manylinux_2_17_x86_64.whl
triton-2.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
```
In the above you can see that `wheel pack` changes the ordering of the tag.

I can look into how exactly `wheel pack` determines the order of the tag, maybe it's not sorting and instead comes down to the ordering in the `WHEEL` file or something.

What package are you running against, I'd love to add a test?

**Comment by adlotsof** [comment]
Essentially it's wheel.exists() returning false where wheel is 'manylinux2014_aarch_64.manylinux_2_17_aarch_64' and the filename 'manylinux_2_17_aarch_64.manylinux2014_aarch_64'. 
(Or vice versa). 
 I will get the exact created filename(how wheel created the .wheel) and the expected (sorted content of variable wheel in the script) filename later.

**Comment by hauntsaninja** [comment]
https://github.com/pypa/wheel/blob/153f6e771fb6d454104d6e60f28fc9d5dbc6c35f/src/wheel/cli/pack.py#L76

https://files.pythonhosted.org/packages/0e/49/2e1bbae4542b8f624e409540b4197e37ab22a88e8685e99debe721cc2b50/triton-2.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

**Comment by hauntsaninja** [comment]
Could you link me to an example wheel file where you get an error?

For example, I'm testing against: https://files.pythonhosted.org/packages/0e/49/2e1bbae4542b8f624e409540b4197e37ab22a88e8685e99debe721cc2b50/triton-2.2.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl

This would let me reproduce and find a fix that works in both cases.

In case useful, here is the place in `wheel pack` where it sorts the tag: https://github.com/pypa/wheel/blob/153f6e771fb6d454104d6e60f28fc9d5dbc6c35f/src/wheel/cli/pack.py#L76

**Comment by adlotsof** [comment]
With the following script i manage to reproduce the error exactly as it happened, using a public package.

```sh
#!/bin/bash

pip install --upgrade pip
rm  ./dist/*
pipPackage=pip
tplatform=manylinux_2_17_aarch64

pip download  "$pipPackage" \
            --ignore-requires-python \
            --implementation cp \
            --only-binary :all: \
            --platform="$tplatform" \
            --no-deps \
            --abi 3 \
            -d ./dist
mv ./dist/pip-24.0-py3-none-any.whl ./dist/pip-24.0-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl

function patchWheelVersion() {
    version="$1"
    if [ -z "$version" ]; then
        echo "No version provided"
        exit 1
    fi
    mkdir ./release
    for platform in $tplatform; do
        path="./dist/"
        for wheel in "$path"*"$platform"*.whl; do
            echo "$wheel"
            ls -l "$wheel"
            newWheel=$(python3 -m change_wheel_version --version "$version" --delete-old-wheel "$wheel") # TODO: if hotfix needed, add --local-version
            if [ -z "$newWheel" ]; then
                echo "failed to change version for $wheel"
                exit 1
            fi
            sleep 1
            mv "$newWheel" ./release || (echo "$newWheel not found?" && exit 1)
            sleep 1
        done
    done
}

patchWheelVersion 1.2.3
```
The output i get is as follows:
```
./dist/pip-24.0-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
-rw-r--r-- 1 tim tim 2110226 Mar 12 13:24 ./dist/pip-24.0-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/tim/wheel-bug/.venv/lib/python3.9/site-packages/change_wheel_version.py", line 172, in <module>
    main()
  File "/home/tim/wheel-bug/.venv/lib/python3.9/site-packages/change_wheel_version.py", line 160, in main
    new_wheel = change_wheel_version(
  File "/home/tim/wheel-bug/.venv/lib/python3.9/site-packages/change_wheel_version.py", line 144, in change_wheel_version
    raise RuntimeError(
RuntimeError: Failed to create new wheel dist/pip-1.2.3-cp37-abi3-manylinux2014_aarch64.manylinux_2_17_aarch64.whl
Directory contents: [PosixPath('dist/pip-24.0-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl'), PosixPath('dist/pip-1.2.3-py3-none-any.whl')]
failed to change version for ./dist/pip-24.0-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
```

**Comment by adlotsof** [comment]
Ah but i see there is a different problem using pip package:
`pip-1.2.3-py3-none-any.whl` is created, while `change_wheel_version` expects `pip-1.2.3-cp37-abi3-manylinux2014_aarch64.manylinux_2_17_aarch64.whl` - in my original case, wheel does add the tags, but in a different order than the input file. Might be the reliance of the tags of the input file is the problem - or maturin when packaging rust into wheels is using a non standart ordering in the filename

**Comment by hauntsaninja** [comment]
Yeah, that's maybe a slightly different case. The wheel tags in that are different between the filename and the WHEEL metadata inside the wheel, not just ordered differently.

I'm still confused about how ordering could be different, given this sorting: https://github.com/pypa/wheel/blob/153f6e771fb6d454104d6e60f28fc9d5dbc6c35f/src/wheel/cli/pack.py#L76
So would be very nice to have a copy of the actual maturin wheel you're playing with

Anyway, maybe you could report what the full output with https://github.com/hauntsaninja/change_wheel_version/pull/3 is? It adds some extra validation that may reveal something interesting

**Comment by adlotsof** [comment]
For the offending wheel, just to confirm:
input file: `-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl`
output file: `-cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64.whl`
expected output filename in error message `-cp37-abi3-manylinux2014_x86_64.manylinux_2_17_x86_64.whl`
contents of `WHEEL`:
```
Wheel-Version: 1.0
Generator: maturin (1.4.0)
Root-Is-Purelib: false
Tag: cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64
```
Looking at code of wheel, i can see following line:
```python    
platforms = sorted({tag.split("-")[2] for tag in tags})
```
now, the tag is `cp37-abi3-manylinux_2_17_aarch64.manylinux2014_aarch64` and the sorting is happening on a string split with `-`. While in change_wheel_version,  
```python
new_tag = "-".join(".".join(sorted(t.split("."))) for t in old_parts.tag.split("-"))
```
so my guess would be the `t.split(".")` is doing something where wheel is behaving differently. 

I try #3 next

**Comment by hauntsaninja** [comment]
Oh very interesting! The `WHEEL` file you have has the platform tags un-expanded, while the [spec says they should be expanded](https://packaging.python.org/en/latest/specifications/binary-distribution-format/#file-contents)

That explains why `wheel pack`'s tag sorting logic doesn't affect your wheel. It might be worth reporting to maturin

Anyway, now that we know what's happening, I can patch this here regardless. Thanks for posting the details!

**Comment by adlotsof** [comment]
Isn't the link you reference also referencing this PEP https://peps.python.org/pep-0425/#compressed-tag-sets ? Wouldn't this be a compressed tag set? 

Off topic:
Thanks a lot for taking the time to have a look, thanks a lot for this script, it's saving me a lot of headache and trying to implement the versioning change myself!

**Comment by hauntsaninja** [comment]
I think that's about the filenames, and the expanded set should be in the WHEEL metadata. From your link:
> To allow for compact filenames of bdists that work with more than one compatibility tag triple, each tag in a filename can instead be a ‘.’-separated, sorted, set of tags.
> ...
> A bdist format that implements this scheme should include the expanded tags in bdist-specific metadata.

In any case, I've updated https://github.com/hauntsaninja/change_wheel_version/pull/3. I think it should work for you, could you test?
